#!/bin/bash

##########################################################################################
#Script Name    : ip_scaner                                                              #
#Description    : Bashscript for ip_scaner with html output                              #
#Args           : -n -o -h -m -u                                                         #
#Author         : Gregor Holzfeind                                                       #
#Email          : gholzfeind@heiniger-ag.ch                                              #
#License        : GNU General Public License v3.0                                        #
#Version        : 0.1                                                                    #
##########################################################################################

#Variable not editabel
var_arpscan="/usr/sbin/arp-scan"
var_nmap="/usr/sbin/arp-scan"
var_arp_scan_file="/tmp/scan.$$"

function func_check() {
	if [[ ! -x $var_arpscan ]]; then #Check is arp-scan install
		printf  "Program \"arp-scan\" is not install\nPlease install \"arp-scan\""
		exit
	fi
  if [[ ! -x $var_nmap ]]; then #Check is nmap install
		printf  "Program \"nmap\" is not install\nPlease install \"nmap\""
		exit
	fi
 	if [ "$EUID" -ne 0 ]; then #Check if the user root
		echo "Please run as root"
		exit
	fi
 }
 
 function func_analye() {
  #ARP-Scan and remove the unused Informations
  arp-scan $var_scan_network | tail -n +3 | head -n -3 > $var_arp_scan_file
  
 }
